-- Seed data for Rush 2026-2027 "Fifty Something" Tour Fan Parties & Meetups
-- Includes active tour stops and balanced example meetups across the tour schedule

INSERT INTO meetups (id, name, tour_city, venue_name, venue_url, address, latitude, longitude, event_date, start_time, description, organizer_name, rsvp_link, category, status, is_example)
VALUES
(
  'sanantonio-01',
  '[Example] Alamo City Pre-Show Fiesta',
  'San Antonio',
  'Frost Bank Center',
  'https://www.frostbankcenter.com',
  '1 AT&T Center Pkwy, San Antonio, TX 78219',
  29.4270,
  -98.4375,
  '2026-09-23',
  '16:00',
  'Tex-Mex tailgate and Rush fan gathering in the Frost Bank Center plaza. Brisket tacos, cold Lone Stars, and a Rush playlist blasting all afternoon.',
  'Alamo City Rush Crew',
  NULL,
  'tailgate',
  'approved',
  1
),
(
  'denver-01',
  '[Example] Mile High Rush Rally',
  'Denver',
  'Ball Arena',
  'https://www.ballarena.com',
  '1000 Chopper Cir, Denver, CO 80204',
  39.7487,
  -105.0077,
  '2026-10-05',
  '15:30',
  'Rocky Mountain pre-show rally outside Ball Arena. Colorado craft brews, mountain air, and a parking lot full of Rush fans.',
  'Mile High Rush Collective',
  NULL,
  'tailgate',
  'approved',
  1
),
(
  'sanjose-01',
  '[Example] Silicon Valley Signals Meetup',
  'San Jose',
  'SAP Center',
  'https://www.sapcenter.com',
  '525 W Santa Clara St, San Jose, CA 95113',
  37.3327,
  -121.9010,
  '2026-10-15',
  '16:00',
  'Bay Area Rush fans converge on SAP Center for a pre-show gathering. Tech meets prog rock — craft cocktails and concert countdown.',
  'Bay Area Rush Network',
  NULL,
  'pub_crawl',
  'approved',
  1
),
(
  'cincinnati-01',
  'Cincinnati Banks Pub Crawl',
  'Cincinnati',
  'The Banks Entertainment District',
  'https://thebankscincy.com',
  '100 Joe Nuxhall Way, Cincinnati, OH 45202',
  39.0975,
  -84.509,
  '2026-10-23',
  '16:30',
  'The pub crawl will take place at the Banks before AND after the 7:30 PM Rush Fifty Something tour show at Heritage Bank Center.',
  'Mark McFadden',
  'https://thebankscincy.com/',
  'pub_crawl',
  'approved',
  0
),
(
  'uncasville-01',
  '[Example] Mohegan Sun Pre-Show Mixer',
  'Uncasville',
  'Mohegan Sun Arena',
  'https://mohegansun.com',
  '1 Mohegan Sun Blvd, Uncasville, CT 06382',
  41.4930,
  -72.0867,
  '2026-10-30',
  '16:00',
  'Casino-resort pre-show gathering at Mohegan Sun. Dinner, drinks, and Rush fans from across New England before the arena show.',
  'New England Rush Syndicate',
  NULL,
  'pub_crawl',
  'approved',
  1
),
(
  'tampa-01',
  '[Example] Tampa Bay Pre-Show Gathering',
  'Tampa',
  'Benchmark International Arena',
  'https://www.ameliearena.com',
  '401 Channelside Dr, Tampa, FL 33602',
  27.9425,
  -82.4519,
  '2026-11-09',
  '16:00',
  'Gulf Coast fan meetup in the Channelside District before the Tampa show. Waterfront drinks, Cuban sandwiches, and Rush all night.',
  'Tampa Bay Rush Coalition',
  NULL,
  'pub_crawl',
  'approved',
  1
)
ON CONFLICT(id) DO UPDATE SET
  name = excluded.name,
  tour_city = excluded.tour_city,
  venue_name = excluded.venue_name,
  venue_url = excluded.venue_url,
  address = excluded.address,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  event_date = excluded.event_date,
  start_time = excluded.start_time,
  description = excluded.description,
  organizer_name = excluded.organizer_name,
  rsvp_link = excluded.rsvp_link,
  category = excluded.category,
  status = excluded.status,
  is_example = excluded.is_example;
