-- Seed data for Rush 2026-2027 "Fifty Something" Tour Fan Parties & Meetups
-- Includes original tour stops + newly added Fall 2026 arena dates

INSERT OR IGNORE INTO meetups (id, name, tour_city, venue_name, address, latitude, longitude, event_date, start_time, description, organizer_name, rsvp_link, category, status)
VALUES
(
  'toronto-01',
  'RushCon Toronto Pre-Show Gathering',
  'Toronto',
  'The Loose Moose Tap & Grill',
  '146 Front St W, Toronto, ON M5J 1G2',
  43.6456,
  -79.3849,
  '2026-08-14',
  '15:00',
  'Official pre-concert fan gathering 2 blocks from Scotiabank Arena. Rush trivia contest, craft beer, and Rush playlist all afternoon.',
  'RushCon Fan Club',
  'https://rushcon.org/toronto2026',
  'tailgate',
  'approved'
),
(
  'toronto-02',
  'YYZ Tribute Band Afterparty',
  'Toronto',
  'Horseshoe Tavern',
  '370 Queen St W, Toronto, ON M5V 2A2',
  43.6499,
  -79.3957,
  '2026-08-14',
  '23:00',
  'Post-concert afterparty featuring live Rush cover set by YYZ Tribute band. Late night poutine & drinks.',
  'Toronto Rush Faithful',
  'https://horseshoetavern.com/events',
  'tribute_band',
  'approved'
),
(
  'chicago-01',
  'Windy City Pre-Show Tailgate & BBQ',
  'Chicago',
  'United Center Lot C',
  '1901 W Madison St, Chicago, IL 60612',
  41.8807,
  -87.6742,
  '2026-08-22',
  '14:00',
  'Big fan tailgate in Lot C with bratwurst, Rush flags, and boomboxes playing bootlegs. Look for the red Starman canopy.',
  'Midwest Rush Mob',
  'https://facebook.com/groups/midwestrushfans',
  'tailgate',
  'approved'
),
(
  'nyc-01',
  'Subdivisions Pub Crawl NYC',
  'New York',
  'The Pennsy Food Hall & Bar',
  '2 Pennsylvania Plaza, New York, NY 10121',
  40.7505,
  -73.9934,
  '2026-09-05',
  '16:00',
  'Gathering right above Penn Station / MSG before the show. Drink specials for fans wearing Rush tour shirts.',
  'NYC Rush Meetup Group',
  'https://meetup.com/nyc-rush-fans',
  'pub_crawl',
  'approved'
),
(
  'cleveland-01',
  'Rock & Roll Hall of Fame Neil Peart Tribute Meetup',
  'Cleveland',
  'Rock & Roll Hall of Fame Plaza',
  '1100 E 9th St, Cleveland, OH 44114',
  41.5085,
  -81.6954,
  '2026-09-12',
  '12:00',
  'Fan photo on the plaza in front of Neil Peart drum exhibit before heading to Rocket Mortgage FieldHouse.',
  'Cleveland Rush Section',
  'https://rockhall.com/events',
  'listening_party',
  'approved'
),
(
  'houston-01',
  'Space City Rush Tailgate (New Tour Date)',
  'Houston',
  'Toyota Center Plaza',
  '1510 Polk St, Houston, TX 77002',
  29.7522,
  -95.3621,
  '2026-10-01',
  '16:30',
  'Newly added tour date celebration! Texas fans pre-show tailgate outside Toyota Center with Texas BBQ & Rush playlist.',
  'Lone Star Rush Society',
  'https://rush.com/tour',
  'tailgate',
  'approved'
),
(
  'stlouis-01',
  'Gateway Arch Fan Gathering (New Tour Date)',
  'St. Louis',
  'Enterprise Center Atrium & Beer Garden',
  '1401 Clark Ave, St. Louis, MO 63103',
  38.6268,
  -90.2026,
  '2026-10-21',
  '16:00',
  'Pre-concert drinks and tour merchandise swap across from Enterprise Center before the newly added St. Louis show.',
  'Gateway Rush Legion',
  'https://rush.com/tour',
  'pub_crawl',
  'approved'
),
(
  'cincinnati-01',
  'Queen City Riverfront Rush Rally (New Tour Date)',
  'Cincinnati',
  'The Banks on Freedom Way',
  '100 Joe Nuxhall Way, Cincinnati, OH 45202',
  39.0975,
  -84.5090,
  '2026-10-23',
  '15:30',
  'Riverfront patio gathering steps away from Heritage Bank Center. Rush trivia, craft taps, and fan prize giveaways.',
  'Ohio Valley Rush Fanatics',
  'https://rush.com/tour',
  'pub_crawl',
  'approved'
),
(
  'pittsburgh-01',
  'Steel City Working Men Meetup (New Tour Date)',
  'Pittsburgh',
  'Souper Bowl Bar & Grill (Across from PPG Paints Arena)',
  '910 5th Ave, Pittsburgh, PA 15219',
  40.4395,
  -79.9893,
  '2026-11-15',
  '16:00',
  'Pre-show gathering for the newly announced November Pittsburgh date. Working Man specials and live Rush concert videos.',
  'Pittsburgh Rush Coalition',
  'https://rush.com/tour',
  'pub_crawl',
  'approved'
),
(
  'la-01',
  'Southern California Signals Tailgate',
  'Los Angeles',
  'Kia Forum Parking Lot E',
  '3900 W Manchester Blvd, Inglewood, CA 90305',
  33.9583,
  -118.3419,
  '2026-06-07',
  '14:00',
  'Tour kickoff celebration outside the Forum. California sunshine, taco trucks, and hundreds of Rush fans.',
  'SoCal Rush Family',
  'https://rush.com/tour',
  'tailgate',
  'approved'
),
(
  'boston-01',
  'Causeway Street Fan Crawl',
  'Boston',
  'The Fours Bar & Hub on Causeway',
  '52 Causeway St, Boston, MA 02114',
  42.3662,
  -71.0621,
  '2026-09-18',
  '16:00',
  'Pre-show gathering right next to TD Garden. Classic rock jukebox takeover and commemorative tour badges.',
  'New England Rush Syndicate',
  'https://rush.com/tour',
  'pub_crawl',
  'approved'
);
